query GetBlogDetail($slug: String!) {
  blogs(filters: { slug: { eq: $slug } }) {
    data {
      id
      attributes {
        createdAt
        body
        slug
        title
        description
        featureImage {
          data {
            attributes {
              url
            }
          }
        }
        categories {
          data {
            attributes {
              Name
              Slug
            }
          }
        }
        author {
          data {
            id
            attributes {
              twitterLink
              githubLink
              linkedInLink
              Bio
              Name
              Photo {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
