query GetRecentBlogs {
  blogs(sort: "createdAt:desc", pagination: { limit: 3 }) {
    data {
      attributes {
        createdAt
        slug
        title
        featureImage {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
