query GetSimilarBlogs($slug: String!, $tags: JSON) {
  blogs(
    filters: { slug: { ne: $slug }, and: { tags: { containsi: $tags } } }
    pagination: { limit: 3 }
  ) {
    data {
      attributes {
        createdAt
        slug
        title
        featureImage {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
